### ISSUE TITLE
Проверить CreditCalculator

### ISSUE THREAD

**Issue by Daaamir2** [Daaamir2/CreditCalculator#1]
Я не смог подобрать алгоритм для решения этого задания, мои результаты не совпадали с результатами banki.ru. Поэтому для примера взял другой сайт с кредитным калькулятором:
https://fincult.info/services/credit-calculator/

**Comment by coursar** [comment]
Задачу для проверки нужно назначать на меня, для этого сбоку есть блок Assignees
